export const actionType = {
    SET_SHOW_SIDEBAR: 'SET_SHOW_SIDEBAR',
    SET_RADIO_PLAY: 'SET_RADIO_PLAY',
    SET_SONG_PLAY: 'SET_SONG_PLAY',
    SET_PLAYLISTS: 'SET_PLAYLISTS',
    SET_CURRENT_SONG: 'SET_CURRENT_SONG',
    SET_CURRENT_INDEX: 'SET_CURRENT_INDEX',
    SET_SRC_AUDIO: 'SET_SRC_AUDIO',
    SET_IS_LOAD: 'SET_IS_LOAD',
    SET_NOTIFY: 'SET_NOTIFY',
    SET_IS_PLAY: 'SET_IS_PLAY',
    SET_IS_LOOP: 'SET_IS_LOOP',
    SET_SONG_INFOR: 'SET_SONG_INFOR',
};
